# Generated by Django 4.2.1 on 2023-05-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Hakaton',
        ),
        migrations.AlterModelOptions(
            name='hakaton',
            options={'verbose_name': 'Хакатон', 'verbose_name_plural': 'Хакатоны'},
        ),
    ]
