# Generated by Django 4.2.1 on 2023-05-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hakaton_anons_hakaton_prizes_alter_hakaton_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakaton',
            name='contact',
            field=models.CharField(max_length=255, null=True, verbose_name='Контакты'),
        ),
    ]
