# Generated by Django 4.2.5 on 2023-09-19 07:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hakaton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Наименование')),
                ('date', models.DateField(null=True, verbose_name='Дата (-ы) проведения')),
                ('rules', models.TextField(null=True, verbose_name='Правила сорвнования')),
                ('anons', models.TextField(null=True, verbose_name='Краткий анонс')),
                ('prizes', models.TextField(null=True, verbose_name='Призы')),
                ('contact', models.CharField(max_length=255, null=True, verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Хакатон',
                'verbose_name_plural': 'Хакатоны',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_team', models.CharField(max_length=255, unique=True, verbose_name='Название команды')),
                ('max_members', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Значение должно быть больше или равно 0'), django.core.validators.MaxValueValidator(4, message='Значение должно быть меньше или равно 4')], verbose_name='Количество участников команды')),
                ('hakaton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='register.hakaton', verbose_name='Хакатон')),
            ],
            options={
                'verbose_name': 'Команду',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_captain', models.BooleanField(verbose_name='Капитан команды')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(11, message='Возраст должен быть больше или равен 11'), django.core.validators.MaxValueValidator(17, message='Возраст должен быть меньше или равен 17')], verbose_name='Возраст')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='register.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Участника',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
