# Generated by Django 4.2.1 on 2023-05-04 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='name_team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='age',
        ),
        migrations.RemoveField(
            model_name='team',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='number_member',
        ),
        migrations.RemoveField(
            model_name='team',
            name='phone',
        ),
        migrations.AddField(
            model_name='member',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='register.team', verbose_name='Команда'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='name_team',
            field=models.CharField(max_length=255, null=True, verbose_name='Название команды'),
        ),
    ]
