# Generated by Django 4.2.5 on 2023-09-22 11:17

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hakaton',
            name='contact',
        ),
        migrations.AddField(
            model_name='hakaton',
            name='telegram',
            field=models.CharField(max_length=255, null=True, validators=[register.models.validate_telegram], verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_captain',
            field=models.BooleanField(default=False, verbose_name='Капитан команды'),
        ),
    ]
