# Generated by Django 4.2.5 on 2023-09-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_hakaton_contact_hakaton_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakaton',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
