# Generated by Django 4.2.1 on 2023-05-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_member_name_team_remove_team_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='max_members',
            field=models.IntegerField(default=4),
        ),
    ]
