# Generated by Django 4.2.1 on 2023-05-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_team_max_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='max_members',
            field=models.IntegerField(max_length=4),
        ),
    ]
