# Generated by Django 4.2.1 on 2023-05-04 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_member_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(11, message='Возраст должен быть больше или равен 11'), django.core.validators.MaxValueValidator(17, message='Возраст должен быть меньше или равен 17')], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='team',
            name='max_members',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Значение должно быть больше или равно 0'), django.core.validators.MaxValueValidator(4, message='Значение должно быть меньше или равно 4')], verbose_name='Количество участников команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name_team',
            field=models.CharField(default=0, max_length=255, unique=True, verbose_name='Название команды'),
            preserve_default=False,
        ),
    ]
