# Generated by Django 4.2.1 on 2023-05-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_member_age_alter_team_max_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_captain',
            field=models.BooleanField(verbose_name='Капитан команды'),
        ),
    ]
