# Generated by Django 4.2.1 on 2023-05-05 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_info_hakaton_alter_hakaton_options'),
        ('register', '0008_alter_member_is_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='hakaton',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='main.hakaton', verbose_name='Хакатон'),
            preserve_default=False,
        ),
    ]
