# Generated by Django 4.2.1 on 2023-05-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_team_hakaton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='hakaton',
        ),
    ]
